version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
    - 8081:3306
    environment:
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
        - mysql_data:/var/lib/mysql/

  wordpress:
    depends_on:
    - mysql
    image: wordpress
    ports:
    - 8080:80
    restart: always
    volumes:
    - ./:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  cli:
    image: klabs/php_cli
    hostname: cli
    container_name: cli
    privileged: true
    user: 66133:513
    volumes:
    - "$SSH_AUTH_SOCK:/ssh-agent:ro"
    - "~/.gitconfig:/home/site/.gitconfig"
    #            - "~/.ssh/config:/home/site/.ssh/config:ro"
    - "~/www:/var/www:rw"
    environment:
    - SSH_AUTH_SOCK=/ssh-agent
    - ENVIRONMENT=dev
    cap_add:
    - SYS_PTRACE

volumes:
  mysql_data:
    driver: local
